import type { DrawingNamespaceSpec } from './types';

const BOX_NEW_ARGS = [
  'left',
  'top',
  'right',
  'bottom',
  'border_color',
  'border_width',
  'border_style',
  'extend',
  'xloc',
  'bgcolor',
  'text',
  'text_size',
  'text_color',
  'text_halign',
  'text_valign',
  'text_wrap',
  'force_overlay',
  'text_font_family',
] as const;

const LINE_NEW_ARGS = [
  'x1',
  'y1',
  'x2',
  'y2',
  'xloc',
  'extend',
  'color',
  'style',
  'width',
  'force_overlay',
] as const;

const LABEL_NEW_ARGS = [
  'x',
  'y',
  'text',
  'xloc',
  'yloc',
  'color',
  'style',
  'textcolor',
  'size',
  'textalign',
  'tooltip',
  'text_font_family',
  'force_overlay',
  'text_formatting',
] as const;

const LINEFILL_NEW_ARGS = ['line1', 'line2', 'color'] as const;

const TABLE_NEW_ARGS = [
  'position',
  'columns',
  'rows',
  'bgcolor',
  'frame_color',
  'frame_width',
  'border_color',
  'border_width',
  'force_overlay',
] as const;

const TABLE_CELL_ARGS = [
  'table_id',
  'column',
  'row',
  'text',
  'width',
  'height',
  'text_color',
  'text_halign',
  'text_valign',
  'text_size',
  'bgcolor',
  'tooltip',
  'text_font_family',
  'text_formatting',
] as const;

export const DRAWING_REGISTRY = {
  box: {
    name: 'box',
    functions: {
      new: {
        canonicalArgs: BOX_NEW_ARGS,
        // registry-correct; standalone helper copy drifts (see runtime-abi.md §3)
        handleFields: {
          left: 'left',
          top: 'top',
          right: 'right',
          bottom: 'bottom',
          border_color: 'border_color',
          border_width: 'border_width',
          border_style: 'border_style',
          extend: 'extend',
          xloc: 'xloc',
          bgcolor: 'bgcolor',
          text: 'text',
          text_size: 'text_size',
          text_color: 'text_color',
          text_halign: 'text_halign',
          text_valign: 'text_valign',
          text_wrap: 'text_wrap',
          force_overlay: 'force_overlay',
          text_font_family: 'text_font_family',
        },
        visualEventArgs: BOX_NEW_ARGS,
      },
      delete: { canonicalArgs: ['id'] },
      set_left: { canonicalArgs: ['id', 'left'] },
      set_right: { canonicalArgs: ['id', 'right'] },
      set_top: { canonicalArgs: ['id', 'top'] },
      set_bottom: { canonicalArgs: ['id', 'bottom'] },
      set_extend: { canonicalArgs: ['id', 'extend'] },
      set_bgcolor: { canonicalArgs: ['id', 'color'] },
      set_border_color: { canonicalArgs: ['id', 'color'] },
      set_border_width: { canonicalArgs: ['id', 'width'] },
      set_text_color: { canonicalArgs: ['id', 'color'] },
      get_left: { canonicalArgs: ['id'] },
      get_right: { canonicalArgs: ['id'] },
      get_top: { canonicalArgs: ['id'] },
      get_bottom: { canonicalArgs: ['id'] },
    },
    constants: [],
  },
  line: {
    name: 'line',
    functions: {
      new: {
        canonicalArgs: LINE_NEW_ARGS,
        // registry-correct; PineJS stub copy drifts (see runtime-abi.md §3)
        handleFields: {
          x1: 'x1',
          y1: 'y1',
          x2: 'x2',
          y2: 'y2',
          xloc: 'xloc',
          extend: 'extend',
          color: 'color',
          style: 'style',
          width: 'width',
          force_overlay: 'force_overlay',
        },
        visualEventArgs: LINE_NEW_ARGS,
      },
      delete: { canonicalArgs: ['id'] },
      set_x2: { canonicalArgs: ['id', 'x2'] },
      set_xy1: { canonicalArgs: ['id', 'x', 'y'] },
      set_xy2: { canonicalArgs: ['id', 'x', 'y'] },
      set_color: { canonicalArgs: ['id', 'color'] },
      get_x2: { canonicalArgs: ['id'] },
      get_y1: { canonicalArgs: ['id'] },
      get_y2: { canonicalArgs: ['id'] },
    },
    constants: [
      { name: 'style_solid', value: 'solid' },
      { name: 'style_dashed', value: 'dashed' },
      { name: 'style_dotted', value: 'dotted' },
      // registry-correct; standalone helper copy drifts (see runtime-abi.md §3)
      { name: 'style_arrow_left', value: 'arrow_left' },
      { name: 'style_arrow_right', value: 'arrow_right' },
      { name: 'style_arrow_both', value: 'arrow_both' },
    ],
  },
  label: {
    name: 'label',
    functions: {
      new: {
        canonicalArgs: LABEL_NEW_ARGS,
        // registry-correct; standalone helper copy drifts (see runtime-abi.md §3)
        handleFields: {
          x: 'x',
          y: 'y',
          text: 'text',
          xloc: 'xloc',
          yloc: 'yloc',
          color: 'color',
          style: 'style',
          textcolor: 'textcolor',
          size: 'size',
          textalign: 'textalign',
          tooltip: 'tooltip',
          text_font_family: 'text_font_family',
          force_overlay: 'force_overlay',
          text_formatting: 'text_formatting',
        },
        visualEventArgs: LABEL_NEW_ARGS,
      },
      delete: { canonicalArgs: ['id'] },
      set_text: { canonicalArgs: ['id', 'text'] },
      get_text: { canonicalArgs: ['id'] },
      set_tooltip: { canonicalArgs: ['id', 'tooltip'] },
      set_textcolor: { canonicalArgs: ['id', 'color'] },
      set_style: { canonicalArgs: ['id', 'style'] },
      set_xy: { canonicalArgs: ['id', 'x', 'y'] },
      set_x: { canonicalArgs: ['id', 'x'] },
      set_y: { canonicalArgs: ['id', 'y'] },
      get_y: { canonicalArgs: ['id'] },
    },
    constants: [
      { name: 'style_none', value: 'none' },
      { name: 'style_xcross', value: 'xcross' },
      { name: 'style_cross', value: 'cross' },
      { name: 'style_triangleup', value: 'triangleup' },
      { name: 'style_triangledown', value: 'triangledown' },
      { name: 'style_flag', value: 'flag' },
      { name: 'style_circle', value: 'circle' },
      { name: 'style_arrowup', value: 'arrowup' },
      { name: 'style_arrowdown', value: 'arrowdown' },
      { name: 'style_square', value: 'square' },
      { name: 'style_diamond', value: 'diamond' },
      { name: 'style_label_up', value: 'label_up' },
      { name: 'style_label_down', value: 'label_down' },
      { name: 'style_label_left', value: 'label_left' },
      { name: 'style_label_right', value: 'label_right' },
      // registry-correct; standalone helper copy drifts (see runtime-abi.md §3)
      { name: 'style_label_lower_left', value: 'label_lower_left' },
      { name: 'style_label_lower_right', value: 'label_lower_right' },
      { name: 'style_label_upper_left', value: 'label_upper_left' },
      { name: 'style_label_upper_right', value: 'label_upper_right' },
      { name: 'style_label_center', value: 'label_center' },
    ],
  },
  linefill: {
    name: 'linefill',
    functions: {
      new: {
        canonicalArgs: LINEFILL_NEW_ARGS,
        handleFields: {
          line1: 'line1',
          line2: 'line2',
          color: 'color',
        },
        visualEventArgs: LINEFILL_NEW_ARGS,
      },
      delete: { canonicalArgs: ['id'] },
      set_color: { canonicalArgs: ['id', 'color'] },
      get_line1: { canonicalArgs: ['id'] },
      get_line2: { canonicalArgs: ['id'] },
    },
    constants: [],
  },
  table: {
    name: 'table',
    functions: {
      new: {
        canonicalArgs: TABLE_NEW_ARGS,
        handleFields: {
          position: 'position',
          columns: 'columns',
          rows: 'rows',
          bgcolor: 'bgcolor',
          frame_color: 'frame_color',
          frame_width: 'frame_width',
          border_color: 'border_color',
          border_width: 'border_width',
          force_overlay: 'force_overlay',
        },
        visualEventArgs: TABLE_NEW_ARGS,
      },
      cell: {
        canonicalArgs: TABLE_CELL_ARGS,
        // registry-correct; standalone helper copy drifts to sparse slots (see runtime-abi.md §3)
        visualEventArgs: TABLE_CELL_ARGS,
      },
      clear: {
        canonicalArgs: [
          'table_id',
          'start_column',
          'start_row',
          'end_column',
          'end_row',
        ],
      },
      merge_cells: {
        canonicalArgs: [
          'table_id',
          'start_column',
          'start_row',
          'end_column',
          'end_row',
        ],
      },
    },
    constants: [],
  },
} as const satisfies Readonly<Record<string, DrawingNamespaceSpec>>;
