import type { InputFnSpec } from './types';

export const INPUT_REGISTRY = {
  input: {
    canonicalArgs: [
      'defval',
      'title',
      'tooltip',
      'inline',
      'group',
      'display',
      'confirm',
      'options',
      'minval',
      'maxval',
      'step',
    ],
  },
  'input.int': {
    canonicalArgs: [
      'defval',
      'title',
      'minval',
      'maxval',
      'step',
      'tooltip',
      'inline',
      'group',
      'display',
      'confirm',
      'options',
    ],
  },
  'input.float': {
    canonicalArgs: [
      'defval',
      'title',
      'minval',
      'maxval',
      'step',
      'tooltip',
      'inline',
      'group',
      'display',
      'confirm',
      'options',
    ],
  },
  'input.bool': {
    canonicalArgs: [
      'defval',
      'title',
      'tooltip',
      'inline',
      'group',
      'display',
      'confirm',
    ],
  },
  'input.string': {
    canonicalArgs: [
      'defval',
      'title',
      'options',
      'tooltip',
      'inline',
      'group',
      'display',
      'confirm',
    ],
  },
  'input.source': {
    canonicalArgs: [
      'defval',
      'title',
      'tooltip',
      'inline',
      'group',
      'display',
      'confirm',
    ],
  },
  'input.color': {
    canonicalArgs: [
      'defval',
      'title',
      'tooltip',
      'inline',
      'group',
      'display',
      'confirm',
    ],
  },
  'input.timeframe': {
    canonicalArgs: [
      'defval',
      'title',
      'options',
      'tooltip',
      'inline',
      'group',
      'display',
      'confirm',
    ],
  },
  'input.session': {
    canonicalArgs: [
      'defval',
      'title',
      'options',
      'tooltip',
      'inline',
      'group',
      'display',
      'confirm',
    ],
  },
  'input.time': {
    canonicalArgs: [
      'defval',
      'title',
      'tooltip',
      'inline',
      'group',
      'display',
      'confirm',
    ],
  },
  'input.symbol': {
    canonicalArgs: [
      'defval',
      'title',
      'tooltip',
      'inline',
      'group',
      'display',
      'confirm',
    ],
  },
  'input.text_area': {
    canonicalArgs: [
      'defval',
      'title',
      'tooltip',
      'inline',
      'group',
      'display',
      'confirm',
    ],
  },
  'input.price': {
    canonicalArgs: [
      'defval',
      'title',
      'minval',
      'maxval',
      'step',
      'tooltip',
      'inline',
      'group',
      'display',
      'confirm',
    ],
  },
} as const satisfies Readonly<Record<string, InputFnSpec>>;
