//@version=5
indicator("LuxAlgo SMT Divergence", overlay=true)

ref = request.security(syminfo.tickerid, "60", close, barmerge.gaps_off, barmerge.lookahead_on)
priceHh = high > high[1]
refHh = ref > ref[1]
priceLl = low < low[1]
refLl = ref < ref[1]

bearSmt = priceHh and not refHh
bullSmt = priceLl and not refLl

plotshape(bearSmt, title="Bear SMT", style=shape.labeldown, location=location.abovebar, color=color.red, text="SMT")
plotshape(bullSmt, title="Bull SMT", style=shape.labelup, location=location.belowbar, color=color.lime, text="SMT")
