import { Buffer } from 'node:buffer';
import {
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { STANDALONE_DRAWING_BUNDLE_GLOBAL } from '../src/runtime/drawing/standalone-bundle.constants';

const ROOT_DIR = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const ENTRYPOINT_PATH = join(
  ROOT_DIR,
  'src/runtime/drawing/standalone-bundle.entry.ts',
);
const ARTIFACT_PATH = join(
  ROOT_DIR,
  'src/runtime/drawing/standalone-bundle.generated.ts',
);

const DISALLOWED_BUNDLE_PATTERNS = [
  { label: 'import', pattern: /\bimport\s/ },
  { label: 'export', pattern: /\bexport\s/ },
  { label: 'new Function', pattern: /\bnew Function\b/ },
] as const;

function renderSpawnOutput(output: Uint8Array<ArrayBufferLike>): string {
  return Buffer.from(output).toString('utf8').trim();
}

function runBunBuild(entryPath: string, outfilePath: string): void {
  const result = Bun.spawnSync({
    cmd: [
      process.execPath,
      'build',
      entryPath,
      '--target=browser',
      '--format=esm',
      '--outfile',
      outfilePath,
    ],
    cwd: ROOT_DIR,
    stdout: 'pipe',
    stderr: 'pipe',
  });

  if (result.exitCode === 0) return;

  const stdout = renderSpawnOutput(result.stdout);
  const stderr = renderSpawnOutput(result.stderr);
  const details = [stdout, stderr].filter(Boolean).join('\n');
  throw new Error(
    `bun build failed for ${relative(ROOT_DIR, entryPath)}${
      details ? `\n${details}` : ''
    }`,
  );
}

export function validateStandaloneDrawingBundle(bundle: string): void {
  for (const { label, pattern } of DISALLOWED_BUNDLE_PATTERNS) {
    if (pattern.test(bundle)) {
      throw new Error(`standalone drawing bundle contains forbidden ${label}`);
    }
  }
}

function appendAliasLayer(bundle: string): string {
  return `${bundle}

var __createDrawingRuntime =
  globalThis.${STANDALONE_DRAWING_BUNDLE_GLOBAL}.createDrawingRuntime;
var __createDrawingStubNamespaces =
  globalThis.${STANDALONE_DRAWING_BUNDLE_GLOBAL}.createDrawingStubNamespaces;
function __createStubNamespaces() {
  return __createDrawingStubNamespaces();
}`.trim();
}

export function buildStandaloneDrawingBundle(): string {
  const tempDir = mkdtempSync(join(tmpdir(), 'pine-drawing-bundle-'));
  const outfilePath = join(tempDir, 'standalone-drawing-bundle.js');

  try {
    runBunBuild(ENTRYPOINT_PATH, outfilePath);
    const rawBundle = readFileSync(outfilePath, 'utf8')
      .replace(/\r\n/g, '\n')
      .trim();
    const bundle = appendAliasLayer(rawBundle);
    validateStandaloneDrawingBundle(bundle);
    return bundle;
  } finally {
    rmSync(tempDir, { recursive: true, force: true });
  }
}

export function renderStandaloneDrawingBundleModule(bundle: string): string {
  return [
    '// Generated by `bun scripts/build-drawing-bundle.ts`. Do not edit by hand.',
    '// biome-ignore format: generated bundle literal',
    '// biome-ignore lint/suspicious/noTemplateCurlyInString: generated bundle literal',
    `export const STANDALONE_DRAWING_BUNDLE = ${JSON.stringify(bundle)};`,
    '',
  ].join('\n');
}

export function writeStandaloneDrawingBundleArtifact(): {
  artifactPath: string;
  bundle: string;
  bundleBytes: number;
} {
  const bundle = buildStandaloneDrawingBundle();
  const moduleSource = renderStandaloneDrawingBundleModule(bundle);

  mkdirSync(dirname(ARTIFACT_PATH), { recursive: true });
  writeFileSync(ARTIFACT_PATH, moduleSource, 'utf8');

  return {
    artifactPath: ARTIFACT_PATH,
    bundle,
    bundleBytes: Buffer.byteLength(bundle, 'utf8'),
  };
}

if (import.meta.main) {
  const { artifactPath, bundleBytes } = writeStandaloneDrawingBundleArtifact();
  console.log(
    `wrote ${relative(ROOT_DIR, artifactPath)} (${bundleBytes} bytes)`,
  );
}
