/**
 * Transpile Command
 *
 * Handles the 'transpile' CLI command for converting Pine Script to JavaScript.
 */

import {
  transpile,
  transpileToPineJS,
  transpileToStandaloneFactory,
} from '../../index.js';
import type { CLIOptions } from '../types';
import { deriveIndicatorId, readInput, writeOutput } from '../utils';

/**
 * Generate PineJS factory code for module export
 */
function generatePineJSFactoryCode(
  pineCode: string,
  indicatorId: string,
  indicatorName?: string,
): string {
  const escapedCode = JSON.stringify(pineCode);
  const nameStr = indicatorName ? JSON.stringify(indicatorName) : 'undefined';

  return `/**
 * PineJS Indicator Factory
 * Generated by pine-transpiler
 *
 * Usage:
 *   import { createIndicator } from './output.js';
 *   const indicator = createIndicator(PineJS);
 */

import { transpileToPineJS } from '@opus-aether-ai/pine-transpiler';

const pineCode = ${escapedCode};
const indicatorId = ${JSON.stringify(indicatorId)};
const indicatorName = ${nameStr};

export function createIndicator(PineJS) {
  const result = transpileToPineJS(pineCode, indicatorId, indicatorName);
  if (!result.success) {
    throw new Error('Transpilation failed: ' + result.error);
  }
  return result.indicatorFactory(PineJS);
}

export default createIndicator;
`;
}

/**
 * Execute the transpile command
 */
export function commandTranspile(
  file: string | undefined,
  options: CLIOptions,
): void {
  if (!file) {
    process.stderr.write('Error: No input file specified\n');
    process.stderr.write('Usage: pine-transpiler transpile <file>\n');
    process.exit(1);
  }

  const code = readInput(file);
  const format = options.format || 'js';

  if (format === 'js') {
    try {
      const result = transpile(code);
      writeOutput(result, options.output);
    } catch (error) {
      process.stderr.write(
        `Transpilation error: ${error instanceof Error ? error.message : String(error)}\n`,
      );
      process.exit(1);
    }
  } else if (format === 'pinejs') {
    const indicatorId = options.id || deriveIndicatorId(file);
    const indicatorName = options.name;

    const result = transpileToPineJS(code, indicatorId, indicatorName);

    if (!result.success) {
      process.stderr.write(`Transpilation error: ${result.error}\n`);
      process.exit(1);
    }

    const factoryCode = generatePineJSFactoryCode(
      code,
      indicatorId,
      indicatorName,
    );
    writeOutput(factoryCode, options.output);
  } else if (format === 'factory') {
    const indicatorId = options.id || deriveIndicatorId(file);
    const indicatorName = options.name;
    const result = transpileToStandaloneFactory(
      code,
      indicatorId,
      indicatorName,
    );
    if (!result.success || !result.factoryCode) {
      process.stderr.write(
        `Transpilation error: ${result.error ?? 'Unknown error'}\n`,
      );
      process.exit(1);
    }
    writeOutput(result.factoryCode, options.output);
  } else {
    process.stderr.write(
      `Error: Unknown format '${format}'. Use 'js', 'pinejs', or 'factory'.\n`,
    );
    process.exit(1);
  }
}
